/*
   Copyright 2019 Evan "Hippy" Slatis

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
package org.hippy.flashcards.flashcardtype;
// Generated Aug 20, 2018 7:04:52 PM by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.NamedAttributeNode;
import javax.persistence.NamedEntityGraph;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hippy.flashcards.flashcard.Flashcard;

/**
 * FlashcardType generated by hbm2java
 */
@Entity
@NamedEntityGraph(name = "FlashcardType.cards", attributeNodes = @NamedAttributeNode("flashcards"))
@Table(name = "flashcard_type", schema = "public", uniqueConstraints = {@UniqueConstraint(columnNames = "card_type"), @UniqueConstraint(columnNames = "title")})
public class FlashcardType implements java.io.Serializable {

	private long id;
    private String cardType;
    private String title;
    private String description;
    private String question;
    private String userAnswerFormat;
	private List<Flashcard> flashcards = new ArrayList<Flashcard>(0);

	/**
	 * 
	 */
	public FlashcardType() {
	}

	/**
	 * @param id
	 * @param type
	 * @param title
	 * @param description
	 * @param flashcards
	 */
	public FlashcardType(long id, String type, String title, String description, String question, String userAnswerFormat, List<Flashcard> flashcards) {
		this.id = id;
		this.cardType = type;
        this.title = title;
        this.description = description;
        this.question = question;
        this.userAnswerFormat = userAnswerFormat;
        this.flashcards = flashcards;
	}

	/**
	 * @return
	 */
	@Column(name = "card_type", unique = true, nullable = false)
    public String getCardType() {
        return this.cardType;
    }

	/**
	 * @return
	 */
	@Column(name = "description")
    public String getDescription() {
        return this.description;
    }

    /**
     * @return
     */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "flashcardType")
    @OrderBy("question ASC")
    public List<Flashcard> getFlashcards() {
        return this.flashcards;
    }

    /**
     * @return
     */
    @Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

    /**
     * @return
     */
    @Column(name = "question")
    public String getQuestion() {
        return this.question;
    }

    /**
     * @return
     */
    @Column(name = "title", unique = true, nullable = false)
    public String getTitle() {
        return this.title;
    }

    /**
     * @return
     */
    @Column(name = "user_answer_format")
    public String getUserAnswerFormat() {
        return this.userAnswerFormat;
    }

    /**
     * @param type
     */
    public void setCardType(String type) {
        this.cardType = type;
    }

    /**
     * @param description
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * @param flashcards
     */
    public void setFlashcards(List<Flashcard> flashcards) {
		this.flashcards = flashcards;
	}

    /**
     * @param id
     */
    public void setId(long id) {
		this.id = id;
	}

    /**
     * @param question
     */
    public void setQuestion(String question) {
        this.question = question;
    }

	/**
	 * @param title
	 */
	public void setTitle(String title) {
        this.title = title;
    }

    /**
     * @param userAnswerFormat
     */
    public void setUserAnswerFormat(String userAnswerFormat) {
        this.userAnswerFormat = userAnswerFormat;
    }

}
