/*
   Copyright 2019 Evan "Hippy" Slatis

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
package org.hippy.flashcards.flashcarduser;
// Generated Aug 20, 2018 7:04:52 PM by Hibernate Tools 3.5.0.Final

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import org.hippy.flashcards.flashcardresults.FlashcardResult;

/**
 * FlashcardUser generated by hbm2java
 */
/**
 * @author Hippy
 */
@Entity
@Table(name = "flashcard_user", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "username"))
public class FlashcardUser implements java.io.Serializable {

	private Long id;
	private String username;
	private String password;
	private Date dateCreated;
	private Date dateModified;
	private List<FlashcardResult> results = new ArrayList<FlashcardResult>(0);

	/**
	 * 
	 */
	public FlashcardUser() {
	}

	/**
	 * @param id
	 * @param name
	 * @param password
	 * @param dateCreated
	 * @param dateModified
	 */
	public FlashcardUser(Long id, String name, String password, Date dateCreated, Date dateModified) {
		this.id = id;
		this.username = name;
		this.password = password;
		this.dateCreated = dateCreated;
		this.dateModified = dateModified;
	}

	/**
	 * @param id
	 * @param name
	 * @param password
	 * @param dateCreated
	 * @param dateModified
	 * @param results
	 */
	public FlashcardUser(Long id, String name, String password, Date dateCreated, Date dateModified, List<FlashcardResult> results) {
		this.id = id;
		this.username = name;
		this.password = password;
		this.dateCreated = dateCreated;
		this.dateModified = dateModified;
		this.results = results;
	}

	/**
	 * @return
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_created", nullable = false, length = 27, insertable=false, updatable=false)
	public Date getDateCreated() {
		return this.dateCreated;
	}

	/**
	 * @return
	 */
	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_modified", nullable = false, length = 27, insertable=false, updatable=false)
	public Date getDateModified() {
		return this.dateModified;
	}

	/**
	 * @return
	 */
	@Id
	@GeneratedValue(strategy=GenerationType.IDENTITY)
	public Long getId() {
		return this.id;
	}

	/**
	 * @return
	 */
	@Column(name = "password", nullable = false)
	public String getPassword() {
		return this.password;
	}

	/**
	 * @return
	 */
	@OneToMany(fetch = FetchType.LAZY, mappedBy = "flashcardUser")
	@OrderBy("dateCreated")
	public List<FlashcardResult> getResults() {
		return this.results;
	}

	/**
	 * @return
	 */
	@Column(name = "username", unique = true, nullable = false)
	public String getUsername() {
		return this.username;
	}

	/**
	 * @param dateCreated
	 */
	public void setDateCreated(Date dateCreated) {
		this.dateCreated = dateCreated;
	}

	/**
	 * @param dateModified
	 */
	public void setDateModified(Date dateModified) {
		this.dateModified = dateModified;
	}

	/**
	 * @param id
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * @param password
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * @param results
	 */
	public void setResults(List<FlashcardResult> results) {
		this.results = results;
	}

	/**
	 * @param username
	 */
	public void setUsername(String username) {
		this.username = username;
	}

}
