/*
   Copyright 2019 Evan "Hippy" Slatis

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
*/
package org.hippy.flashcards.flashcard;
// Generated Aug 20, 2018 7:04:52 PM by Hibernate Tools 3.5.0.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hippy.flashcards.flashcardtype.FlashcardType;

/**
 * Flashcard generated by hbm2java
 */
@Entity
@Table(name = "flashcard", schema = "public")
public class Flashcard implements java.io.Serializable {

	private long id;
	private FlashcardType flashcardType;
	private String question;
	private String answer;

	/**
	 * 
	 */
	public Flashcard() {
	}

	/**
	 * @param id
	 * @param flashcardType
	 * @param question
	 * @param answer
	 */
	public Flashcard(long id, FlashcardType flashcardType, String question, String answer) {
		this.id = id;
		this.flashcardType = flashcardType;
		this.question = question;
		this.answer = answer;
	}

	/**
	 * @return
	 */
	@Id
	@Column(name = "id", unique = true, nullable = false)
	public long getId() {
		return this.id;
	}

	/**
	 * @param id
	 */
	public void setId(long id) {
		this.id = id;
	}

	/**
	 * @return
	 */
	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "card_type", nullable = false)
	public FlashcardType getFlashcardType() {
		return this.flashcardType;
	}

	/**
	 * @param flashcardType
	 */
	public void setFlashcardType(FlashcardType flashcardType) {
		this.flashcardType = flashcardType;
	}

	/**
	 * @return
	 */
	@Column(name = "question", nullable = false)
	public String getQuestion() {
		return this.question;
	}

	/**
	 * @param question
	 */
	public void setQuestion(String question) {
		this.question = question;
	}

	/**
	 * @return
	 */
	@Column(name = "answer", nullable = false)
	public String getAnswer() {
		return this.answer;
	}

	/**
	 * @param answer
	 */
	public void setAnswer(String answer) {
		this.answer = answer;
	}

}
